#!/usr/bin/perl -w

use strict;
use warnings;
use rlib ('../lib');
use config;
use modules;

# Konfigurationsdatei einlesen
my $cfg = uhccfg();

# Werte einlesen
my $sleep = $cfg->val( 'hk2_vl', 'time' );
my $aktor_mischer_hk2 = $cfg->val( 'hk2_vl','mischer_hk2' );
my $sensor_hk2 = $cfg->val( 'hk2_vl', 'sensor_hk2');
my $pumpe_hk2 = $cfg->val( 'hk2_vl' , 'pumpe_hk2' );

while(1) {

# Betriebzustand der Heizkreispumpe auslesen
my $pumpe_hk2 = sql_getvalue('wired',$pumpe_hk2,'STATE');

	# Mischer regelt nur bei Hauptrelais Hk2 = true
	if ($pumpe_hk2 == 1) {

	# Werte einlesen und formatieren
   	my $vorlauf_soll = sql_getvalue('uhc','Vorlaufsoll','temperature');
   	my $vorlauf_ist = sql_getvalue('owfs',$sensor_hk2,'temperature');
   	my $mischer_hk2 = sql_getvalue('wired',$aktor_mischer_hk2,'LEVEL');
	
	# Berechnung Regelbereich fein
	my $vorlauf_oben_o = ($vorlauf_soll + 2);
	my $vorlauf_oben_u = ($vorlauf_soll + 0.5);
	my $vorlauf_unten_u = ($vorlauf_soll - 2);
	my $vorlauf_unten_o = ($vorlauf_soll - 0.5);

	# Regelung Mischer Heizkreis 2
		# Mischer 0.5 % auf, wenn Vorlauftemperatur im Feinregelbereich -2 bis -0.5
		if (($vorlauf_ist >= $vorlauf_unten_u) && ($vorlauf_ist < $vorlauf_unten_o)){
        		my $mischer_w1 = sprintf("%.3f", ($mischer_hk2 + 0.005));
        		xmlrpc_setvalue('wired',$aktor_mischer_hk2,'LEVEL',$mischer_w1);
		}
		# Mischer 3% auf, wenn Vorlauftemperatur außerhalb Feinregelbereich
		if (($vorlauf_ist < $vorlauf_unten_u) && ($mischer_hk2 < 1)) {
        		my $mischer_w2 = sprintf("%.3f", ($mischer_hk2 + 0.03));
	 		xmlrpc_setvalue('wired',$aktor_mischer_hk2,'LEVEL',$mischer_w2);
		}	
		# Mischer 0.5 % zu, wenn Vorlauftemperatur im Feinregelbereich 2 bis 0.5
		if (($vorlauf_ist > $vorlauf_oben_u) && ($vorlauf_ist <= $vorlauf_oben_o)){
        		my $mischer_k1 = sprintf("%.3f", ($mischer_hk2 - 0.005));
			xmlrpc_setvalue('wired',$aktor_mischer_hk2,'LEVEL',$mischer_k1);
		}
		# Mischer 3% zu, wenn Vorlauftemperatur außerhalb Feinregelbereich
		if (($vorlauf_ist > $vorlauf_oben_o) && ($mischer_hk2 > 0)){
        		my $mischer_k2 = sprintf("%.3f", ($mischer_hk2 - 0.03));
 			xmlrpc_setvalue('wired',$aktor_mischer_hk2,'LEVEL',$mischer_k2);
		}
	}
sleep($sleep);
}
